name: academic_calendar
description: Academic Calendar app
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  shared_preferences: ^2.3.2
flutter:
  uses-material-design: true
